name: Local CI/CD Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.LOCAL_SSH_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H 192.168.1.110 >> ~/.ssh/known_hosts

    - name: Deploy to local server
      run: |
        ssh -i ~/.ssh/id_ed25519 legat@192.168.1.110 << 'EOF'
          cd C:\Users\legat\OneDrive\Desktop\Projects\demo\CI-CD\cicd
          git pull origin main
          C:\Users\legat\OneDrive\Desktop\Projects\demo\CI-CD\venv\Scripts\activate
          pip install -r requirements.txt
          python manage.py migrate
          python manage.py collectstatic --noinput
          echo "Deployment successful!"
        EOF